# project-root/config.yaml

# ROS 2 settings
ros_distro: humble
ros_domain_id: 0

# Image build & push
image_prefix: pancake                    # images: myrobot_<component>:latest
registry: docker.io/dragomirxyz
base_image:  docker.io/dragomirxyz/robocore_humble_arm64:latest
# Deployment mode: "image" or "live"
deploy_mode: live
build_dir: build

mount_root: /home/cdr/ros_builds
# Where to find components
components_dir: components

# Compose file to generate/use
compose_file: docker-compose.yml

# All your target hosts
host:
  name: raspberrypi5
  ip: pi5.local
  user: cdr
  arch: arm64